version: "3.8"

services:
  ws1:
    image: nginx:alpine
    volumes:
      - ./ws1:/usr/share/nginx/html
      - ./ws1/me.jpg:/usr/share/nginx/html/me.jpg
    networks:
      - backend

  ws2:
    image: nginx:alpine
    volumes:
      - ./ws2:/usr/share/nginx/html
    networks:
      - backend

  ws3:
    image: nginx:alpine
    volumes:
      - ./ws3:/usr/share/nginx/html
    networks:
      - backend

  reverse_proxy:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - ws1
      - ws2
      - ws3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
